{"uuid": "51e6259b-ee0e-48aa-9d98-4d27e69e442e", "children": ["a47bbd11-644d-4e10-979d-c561dc37c202"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "trace": "  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\tests\\conftest.py\", line 30, in login\n    login_page.login(config[\"username\"], config[\"password\"])\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\pages\\login_page.py\", line 19, in login\n    self.enter_text(self.EMAIL, username)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\pages\\base_page.py\", line 29, in enter_text\n    element = self.wait.until(EC.element_to_be_clickable(locator))\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 129, in until\n    value = method(self._driver)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 624, in _predicate\n    target = driver.find_element(*target)  # grab element at locator\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 922, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 451, in execute\n    response = cast(RemoteConnection, self.command_executor).execute(driver_command, params)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 404, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 428, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\_request_methods.py\", line 143, in request\n    return self.request_encode_body(\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\_request_methods.py\", line 278, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 459, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 474, in increment\n    raise reraise(type(error), error, _stacktrace)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\util\\util.py\", line 38, in reraise\n    raise value.with_traceback(tb)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 534, in _make_request\n    response = conn.getresponse()\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\connection.py\", line 565, in getresponse\n    httplib_response = super().getresponse()\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\lib\\http\\client.py\", line 1368, in getresponse\n    response.begin()\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\lib\\http\\client.py\", line 317, in begin\n    version, status, reason = self._read_status()\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\lib\\http\\client.py\", line 278, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\lib\\socket.py\", line 705, in readinto\n    return self._sock.recv_into(b)\n"}, "steps": [{"name": "Loading login page: 'https://smiligencehr.itsfortesza.com'", "status": "passed", "parameters": [{"name": "url", "value": "'https://smiligencehr.itsfortesza.com'"}], "start": 1753869625833, "stop": 1753869640521}, {"name": "Logging in with username: 'admin@gmail.com'", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "trace": "  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\pages\\login_page.py\", line 19, in login\n    self.enter_text(self.EMAIL, username)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\pages\\base_page.py\", line 29, in enter_text\n    element = self.wait.until(EC.element_to_be_clickable(locator))\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 129, in until\n    value = method(self._driver)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 624, in _predicate\n    target = driver.find_element(*target)  # grab element at locator\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 922, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 451, in execute\n    response = cast(RemoteConnection, self.command_executor).execute(driver_command, params)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 404, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 428, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\_request_methods.py\", line 143, in request\n    return self.request_encode_body(\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\_request_methods.py\", line 278, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 459, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 474, in increment\n    raise reraise(type(error), error, _stacktrace)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\util\\util.py\", line 38, in reraise\n    raise value.with_traceback(tb)\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 534, in _make_request\n    response = conn.getresponse()\n  File \"C:\\Users\\User\\PycharmProjects\\SmiligenceHrAdmin\\.venv\\lib\\site-packages\\urllib3\\connection.py\", line 565, in getresponse\n    httplib_response = super().getresponse()\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\lib\\http\\client.py\", line 1368, in getresponse\n    response.begin()\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\lib\\http\\client.py\", line 317, in begin\n    version, status, reason = self._read_status()\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\lib\\http\\client.py\", line 278, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\lib\\socket.py\", line 705, in readinto\n    return self._sock.recv_into(b)\n"}, "parameters": [{"name": "username", "value": "'admin@gmail.com'"}, {"name": "password", "value": "'Welcome@l1'"}], "start": 1753869640522, "stop": 1753869657755}], "start": 1753869625824, "stop": 1753869657918}], "start": 1753869625824, "stop": 1753869658457}